spring:
  application:
    name: translation-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

server.port: 9999

logging:
  level:
    root: INFO

yandex:
  api:
    key: ${YANDEX_API_KEY}
  cloud:
    folder:
      id: ${YANDEX_CLOUD_FOLDER_ID}